name: Installer Build

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:

jobs:
  versions:
    name: Check Version Number
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        # This is coment
        echo "I'm build workflow"
        # This is comment 2
        echo "After comment"
