name: Debug
on:
  workflow_dispatch:
  
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Debug
      run: |
        echo "Current commit: ${GITHUB_REF}"
        echo "Test commit: $(git rev-parse --short HEAD)"
