name: Deploy PR as ECS Service

on:
  workflow_run:
    workflows: ["Installer Build"]
    types: [completed]
  workflow_dispatch:
    inputs:
      target_app_server:
        required: false
        description: "Configuration"
        type: choice
        default: ''
        options:
        - WildFly
        - WebLogic
        - Both
      db_seed_file:
        required: false
        default: ''
        description: "The seed sql file name in folder liquibase/sql/seed, example: additional-domain.sql"

env:
  AWS_REGION: us-east-1  
  ECS_CLUSTER: qa

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event.inputs) }}
    outputs:
      branch: ${{ steps.setup.outputs.branch }}
      pr: ${{ steps.setup.outputs.pr }}
      target_app_server: ${{ steps.setup.outputs.target_app_server }}
      db_seed_file: ${{ steps.setup.outputs.db_seed_file }}
    steps:
      - name: Prepare variables
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            branch="${{ github.event.workflow_run.head_branch }}"
            echo "branch=${branch}" >> $GITHUB_OUTPUT
            if [[ "${{ github.event.workflow_run.pull_requests }}" != "" ]]; then
              pr="${{ github.event.workflow_run.pull_requests[0].number }}"
            else
              pr=""
            fi
            target_app_server=""
            db_seed_file=""
          else
            branch="${GITHUB_REF#refs/heads/}"
            pr=""
            target_app_server="${{ github.event.inputs.target_app_server }}"
            db_seed_file="${{ github.event.inputs.db_seed_file }}"
          fi
          echo "Branch: ${branch}"
          echo "PR: ${pr}"
          echo "Target app server: ${target_app_server}"
          echo "Data seed file: ${db_seed_file}"
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "pr=$pr" >> $GITHUB_OUTPUT
          echo "target_app_server=$target_app_server" >> $GITHUB_OUTPUT
          echo "db_seed_file=$db_seed_file" >> $GITHUB_OUTPUT
