name: Release
on:
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        git log --grep="Merge" --pretty=oneline -1
        pr=$(git log --grep="Merge pull request #[0-9]\+" --pretty=oneline -1
        pr=$(git log --grep="Merge pull request #[0-9]\+" --pretty=oneline -1
