name: Release
on:
  workflow_dispatch:
    branches:
      - '**'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        git log --grep="Merge" --pretty=oneline -1
        pr=$(git log --grep="Merge pull request #[0-9]\+" --pretty=oneline -1 | sed -e "s/.*Merge pull request .*#//g" | sed -e "s/ .*//g")
        echo $pr
