name: Release
on:
  workflow_dispatch:
    branches:
      - '**'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git log --merges > log.txt
        ls -l
        cat log.txt
        git --version
        git log --help
