name: Release
on:
  push:
    branches:
      - master

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo ${{ env.GITHUB_PR_NUMBER }}
