name: Release
on:
  push:
    branches:
      - master

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
