name: Release
on:
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        echo "start"
        echo "$(git rev-parse --short HEAD)"
        sed -i "s/GITHUB_SHA=\"\";/GITHUB_SHA=\"$(git rev-parse --short HEAD)\";/g" Test.java
        echo "end"
        cat Test.java
