name: Release
on:
  workflow_dispatch:
    branches:
      - '**'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git --version
        git log --grep="Merge" --pretty=oneline -1
        git --version
        git log --grep=Merge --pretty=oneline -1
        git --version
        git log --pretty=oneline -1
