name: Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  release:
    if: github.event.pull_request.merged == true
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: Parse PR number from latest commit message
      run: |
        echo The merged PR number is "${{ github.event.pull_request.number }}"
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        pr: ${{ github.event.pull_request.number }}
        search_artifacts: true
    - name: verify
      run: |
        ls
        cat test.txt
        cat My-pr-${{ github.event.pull_request.number }}/test.txt
